[[Network]]
Name = "Default Network"
ID = "default"
Interface = "wg0"
ApproveExpiry = "1h0m0s"
ActivateExpiry = "5m"

[[Network]]
Name = "Another Network"
ID = "anet"
Interface = "wg1"
ApproveMode = "AUTO"

[[Network]]
Name = "ChaosNet"
ID = "chaos"
Interface = "wg2"
ApproveMode = "AUTO"
ActivateMode = "AUTO"
